version: '3.7'
services:
  api:
    container_name: fungie_api
    platform: linux/amd64
    build: .
    depends_on:
      - fungie-redis
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - REDIS_URL=fungie_redis:6379
    networks:
      - fungie_network
    tty: true
  fungie-redis:
    container_name: fungie_redis
    image: redis:7.0.5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - fungie_network
    tty: true
networks:
  fungie_network:
    driver: bridge
volumes:
  redis_data:
    driver: local
