// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Message struct {
	ID      string `json:"id"`
	Message string `json:"message"`
}

// UserInput allows us to filter users by their ID or username
type UserInput struct {
	// Unique identifier for the user, in the form of a universally unique identifier (UUID)
	ID *string `json:"id"`
	// The user's handle or username, used for identifying the user within the application
	Username *string `json:"username"`
}
